"use client"

import { updateMembership } from "@/app/actions/membership"
import { useState, useTransition } from "react"

type Membership = { name: string; price: number; chemicalDiscount: number; monthlyCuts: number; description: string; active: boolean }

export function AdminMembership({ membership }: { membership: Membership }) {
  const [form, setForm] = useState(membership)
  const [message, setMessage] = useState("")
  const [isPending, startTransition] = useTransition()
  function save() { startTransition(async () => { const result = await updateMembership(form); setMessage(result.ok ? "Membresía actualizada." : result.error ?? "No se pudo guardar.") }) }
  return <section className="max-w-2xl"><div className="mb-8"><p className="text-xs uppercase tracking-[0.3em] text-primary">Configuración comercial</p><h2 className="mt-2 font-serif text-4xl text-foreground">Corte + Fino</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Definí los beneficios que se muestran en la tercera sección del sitio.</p></div><div className="grid gap-4 rounded-2xl border border-border bg-card p-5 sm:grid-cols-2 sm:p-6"><label className="flex flex-col gap-2 text-sm text-foreground">Nombre<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="min-h-11 rounded-lg border border-input bg-background px-3 text-base" /></label><label className="flex flex-col gap-2 text-sm text-foreground">Precio mensual<input type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: Number(e.target.value) })} className="min-h-11 rounded-lg border border-input bg-background px-3 text-base" /></label><label className="flex flex-col gap-2 text-sm text-foreground">Descuento químicos (%)<input type="number" min="0" max="100" value={form.chemicalDiscount} onChange={(e) => setForm({ ...form, chemicalDiscount: Number(e.target.value) })} className="min-h-11 rounded-lg border border-input bg-background px-3 text-base" /></label><label className="flex flex-col gap-2 text-sm text-foreground">Cortes mensuales<input type="number" min="1" value={form.monthlyCuts} onChange={(e) => setForm({ ...form, monthlyCuts: Number(e.target.value) })} className="min-h-11 rounded-lg border border-input bg-background px-3 text-base" /></label><label className="flex flex-col gap-2 text-sm text-foreground sm:col-span-2">Descripción<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={3} className="rounded-lg border border-input bg-background px-3 py-3 text-base leading-6" /></label><label className="flex items-center gap-3 text-sm text-foreground sm:col-span-2"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} className="size-5 accent-primary" /> Mostrar membresía en el sitio</label><div className="flex items-center gap-4 sm:col-span-2"><button type="button" onClick={save} disabled={isPending} className="min-h-11 rounded-full bg-primary px-6 text-sm text-primary-foreground">{isPending ? "Guardando..." : "Guardar cambios"}</button>{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}</div></div></section>
}
